version: '3'

services:
  php:
    build:
      context: php
      dockerfile: Dockerfile
    volumes:
      - ./html/:/var/www/html/
    restart: always
    ports:
      - 8080:80
    links:
      - mysql

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: sayhi
      MYSQL_ROOT_PASSWORD: sayhi
      MYSQL_DATABASE: appDB
    command: ['--default-authentication-plugin=mysql_native_password']
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql-init/:/docker-entrypoint-initdb.d/:ro

volumes:
  mysql: